livingroom_window:
  name: Livingroom Window
  host: 'yeelink-light-color2_miap91ae'
  type: yeelight
livingroom_kitchen:
  name: Livingroom Kitchen
  host: 'yeelink-light-color2_miapb81f'
  type: yeelight
bedroom:
  name: Bedroom
  host: 'yeelink-light-color2_miapa322'
  type: yeelight
