livingroom_window:
  name: Livingroom Window
  host: 192.168.1.216
  type: yeelight
livingroom_kitchen:
  name: Livingroom Kitchen
  host: 192.168.1.213
  type: yeelight
bedroom:
  name: Bedroom
  host: 192.168.1.186
  type: yeelight
