lights:
  livingroom_window:
    name: Livingroom Window
    host: yeelink-light-color2-miap91ae
    type: yeelight
  livingroom_kitchen:
    name: Livingroom Kitchen
    host: yeelink-light-color2-miapb81f
    type: yeelight
  bedroom:
    name: Bedroom
    host: yeelink-light-color2-miapa322
    type: yeelight
presets:
  asdfggg:
    livingroom_window:
      power: 'on'
      brightness: '40'
      color:
        r: 214
        g: 211
        b: 19
    livingroom_kitchen:
      power: 'on'
      brightness: '100'
      color:
        r: 255
        g: 145
        b: 0
    bedroom:
      power: 'on'
      brightness: '6'
      color:
        r: 247
        g: 236
        b: 222
  asdfgggff:
    livingroom_window:
      power: 'on'
      brightness: '40'
      color:
        r: 214
        g: 211
        b: 19
    livingroom_kitchen:
      power: 'on'
      brightness: '100'
      color:
        r: 255
        g: 145
        b: 0
    bedroom:
      power: 'on'
      brightness: '6'
      color:
        r: 247
        g: 236
        b: 222
  a:
    livingroom_window:
      power: 'on'
      brightness: '40'
      color:
        r: 214
        g: 211
        b: 19
    livingroom_kitchen:
      power: 'on'
      brightness: '100'
      color:
        r: 255
        g: 145
        b: 0
    bedroom:
      power: 'on'
      brightness: '6'
      color:
        r: 247
        g: 236
        b: 222
